# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Pulling
      uses: actions/checkout@v4

    - name: Installing bun
      run: npm install -g bun

    - name: Installing deps
      run: bun install --frozen-lockfile --production

    - name: build
      run: bun run build

    - name: upload
      uses: actions/upload-artifact@v4
      with: 
          name: build
          path: ./dist
